import 'package:quiz/components/question.dart';

// Leave as var, so that way the correct answers can be sorted.
var quiz4 = [
  MultipleAnswersQuestion(
    "Kendra has been your neighbor for 10 years now and you enjoy spending time with her. For years, both of your families have done many things together.",
    "What social tag(s) apply to Kendra?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["In-Person Friend",],
  ),
  MultipleAnswersQuestion(
    "Amber is in your science class and she always seems to have the answers to the questions asked by your teacher. You never see Amber outside of class. What social tag(s) apply to Amber?",
    "What social tag(s) apply to Amber?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["School Peer",],
  ),
  MultipleAnswersQuestion(
    "Andrew works with you at McDonalds. He taught you everything you know about flipping patties. While talking at work you discovered he loves playing chess just like you do! Ever since you learned about his passion, you’ve been playing chess and eating Wendy’s every weekend.",
    "What social tag(s) apply to Andrew?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["In-Person Friend", "Work Peer",],
  ),
  MultipleAnswersQuestion(
    "Charlie and his family moved to your neighborhood 6 months ago. Last month you recognized Charlie at Church and decided to welcome him. You have since then seen him every Sunday but you don’t know much about him.",
    "What social tag(s) apply to Charlie?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Acquaintance",],
  ),
  MultipleAnswersQuestion(
    "Dr. Cole teaches your favorite math class.",
    "What social tag(s) apply to Dr. Cole?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Boss / Teacher",],
  ),
  MultipleAnswersQuestion(
    "Hannah is a job coach who you see weekly. You think Hannah is very attentive and always does her best to help you. ",
    "What social tag(s) apply to Hannah?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Personal Service Provider",],
  ),
  MultipleAnswersQuestion(
    "Jenna got hired by your employer a year after you did. Your supervisor has asked you to train her. You've never seen her outside of work. ",
    "What social tag(s) apply to Jenna?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Work Peer",],
  ),
  MultipleAnswersQuestion(
    "Last week when grocery shopping, you dropped your shopping basket, dropping all of the fruits. A young man walking behind you with his daughter, saw what happened and helped you pick up your fruit. He said his name was Thomas. ",
    "What social tag(s) apply to Thomas?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Stranger"],
  ),
  MultipleAnswersQuestion(
    "Michelle is taking the same algebra class as you do. You’ve both struggled on learning new concepts and thought it would be a good idea to work together on homework. You’ve both gotten really good at algebra and now hang out after school.",
    "What social tag(s) apply to Michelle?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["In-Person Friend", "School Peer",],
  ),
  MultipleAnswersQuestion(
    "You first met Eric while playing Minecraft. He was super good at it and you asked him to teach you how to build impressive things. While talking through the in-game feature you learned that Eric has your same age and you share the same interests. You now enjoy spending time while playing with Eric and even play other games together.",
    "What social tag(s) apply to Eric?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Online Friend",],
  ),
  MultipleAnswersQuestion(
    "You love to spend time with your little brother Andrew. Andrew wants to spend more time with you, so he got a job at the same store where you work. ",
    "What social tag(s) apply to Andrew?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Family", "Work Peer",],
  ),
  MultipleAnswersQuestion(
    "Your Grandma May has signed up for a Facebook account and sent you a friend request. You remember that last year during Thanksgiving dinner, she mentioned something about wanting to communicate more often with her grandkids.",
    "What social tag(s) apply to Grandma May?",
    "no",
    [
      "Family",
      "In-Person Friend",
      "School Peer",
      "Personal Service Provider",
      "Work Peer",
      "Boss / Teacher",
      "Online Friend",
      "Acquaintance",
      "Community Helper",
      "Stranger"
    ],
    ["Family",],
  ),
];
